# used to automatically push and deploy our app onto the azure service
# make sure to update the publish profile on the repo when adding to a new app service
name: Build and Deploy Full Stack

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-frontend:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://ghcr.io/
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Lowercase the repo name and username
      run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
        file: frontend/Dockerfile
        context: ./frontend

  deploy-frontend:
    needs: build-frontend

    permissions:
      contents: none
    runs-on: ubuntu-latest

    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: allanterrafrontend
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND }}
          images: 'ghcr.io/${{ env.REPO }}:${{ github.sha }}'
  
  build-backend:
    needs: deploy-frontend
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://ghcr.io/
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Lowercase the repo name and username
      run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
        file: backend/backend/Dockerfile
        context: ./backend

  deploy-backend:
    needs: build-backend

    permissions:
      contents: none
    runs-on: ubuntu-latest

    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: allanterrabackend
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
          images: 'ghcr.io/${{ env.REPO }}:${{ github.sha }}'